services:
  - type: web
    name: booktracker-web
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free 
 envVars:
      - key: MONGODB_URI
        sync: false
